//! utoipa-generated `OpenAPI` document for the broker's OWUI-facing surface (D10).
//!
//! The broker is the front door OWUI talks to. Its document combines the broker-owned
//! handlers (probes, `/api/config`, `/api/status`, sandbox CRUD) with the runtime surface
//! (`/execute`, `/files/*`, `/snapshot`, `/restore`, `/api/terminals*`) that OWUI reaches
//! through the broker's reverse proxy — issue #75 **Q1 = "all"**. The runtime handlers
//! are annotated in [`runtime::openapi`] and merged in here via [`OpenApi::merge`].
//!
//! `info.version` is the broker crate version: utoipa fills `info.version`/`info.license`
//! from `CARGO_PKG_VERSION`/`CARGO_PKG_LICENSE` at compile time, so it tracks
//! [`crate::version()`] (issue #75 **Q4**). The structural shape is guarded by
//! `tests/openapi_snapshot.rs` (issue #75 **Q2**). The catch-all reverse proxy
//! (`/{*path}`) and the `/api/terminals/{id}` WebSocket upgrade are intentionally omitted
//! from `paths` — they are not ownable REST contracts (issue #75 **Q5**).
//!
//! `paths(...)` references handlers by full path so the per-handler `__path_*` items
//! (generated by `#[utoipa::path]` in `crate::api`) resolve.

#![forbid(unsafe_code)]

use shared::BearerAddon;
use utoipa::OpenApi;

// Schema types referenced by `components(schemas(...))`.
use crate::api::{
    ConfigResponse, CreateSandboxRequest, Features, HealthResponse, SandboxObject, StatusResponse,
};

/// The merged broker + runtime `OpenAPI` document.
///
/// `paths(...)` lists the broker-owned handlers; the runtime handlers are pulled in by
/// merging [`runtime::openapi`] in [`openapi_document`]. The shared Bearer security
/// scheme (so gated paths show the 🔒 and open probes show none) is registered via
/// [`BearerAddon`].
#[derive(OpenApi)]
#[openapi(
    info(
        title = "open-websandbox broker",
        description = "Open WebUI front door + Kubernetes Sandbox lifecycle. \
The runtime tool surface (/execute, /files/*, /snapshot, /restore, /api/terminals*) is \
proxied to the resolved sandbox pod and documented here as part of the OWUI-facing contract. \
The catch-all reverse proxy (/{*path}) and the /api/terminals/{id} WebSocket upgrade are \
opaque passthroughs omitted from this document (issue #75 Q5)."
    ),
    paths(
        crate::api::healthz,
        crate::api::readyz,
        crate::api::metrics,
        crate::api::openapi_json,
        crate::api::docs,
        crate::api::api_config,
        crate::api::api_status,
        crate::api::create_sandbox,
        crate::api::list_sandboxes,
        crate::api::get_sandbox,
        crate::api::delete_sandbox
    ),
    components(schemas(
        HealthResponse, ConfigResponse, Features, StatusResponse,
        CreateSandboxRequest, SandboxObject,
        shared::SandboxSpec, shared::SandboxStatus, shared::SandboxCondition,
        shared::OperatingMode, shared::ShutdownPolicy, shared::Profile
    )),
    modifiers(&BearerAddon),
    tags(
        (name = "health", description = "Liveness / readiness / metrics probes"),
        (name = "docs", description = "OpenAPI document + Scalar UI"),
        (name = "broker", description = "Broker-served gated surface (/api/config, /api/status)"),
        (name = "sandboxes", description = "Sandbox lifecycle CRUD"),
        (name = "execute", description = "Hardened command execution (runtime, proxied)"),
        (name = "files", description = "Workspace filesystem surface (runtime, proxied)"),
        (name = "ports", description = "Host-port introspection (runtime, proxied; restricted)"),
        (name = "snapshot", description = "S3-tiered workspace offload/restore (runtime, proxied)"),
        (name = "terminals", description = "Interactive PTY terminals HTTP CRUD (runtime, proxied)"),
        (name = "tools", description = "LLM-tool download/list/exists/upload (runtime, proxied)")
    )
)]
pub struct ApiDoc;

/// Build the OWUI-facing `OpenAPI` document: broker paths + schemas, the runtime surface
/// merged in, and the Bearer scheme registered. `info.version` tracks the broker crate
/// version (utoipa fills it from `CARGO_PKG_VERSION` at compile time = `crate::version()`).
#[must_use]
pub fn openapi_document() -> utoipa::openapi::OpenApi {
    let mut doc = ApiDoc::openapi();
    // Pull in the runtime surface (issue #75 Q1 = "all"); the broker reverse-proxies
    // these paths to the resolved pod, so they ARE part of the OWUI-facing contract.
    doc.merge(runtime::openapi::openapi_document());
    doc
}
