//! utoipa-generated OpenAPI document for the runtime's tool surface (D10).
//!
//! These paths (`/execute`, `/files/*`, `/snapshot`, `/restore`, `/api/terminals*`,
//! `/download`, `/list`, `/exists`, `/upload`, `/ports`) are OWUI-reachable through the
//! broker's reverse proxy, so the broker merges this document into its OWUI-facing
//! surface (issue #75 **Q1 = "all"**). The `/api/terminals/{id}` WebSocket upgrade is
//! omitted (issue #75 **Q5**): only the HTTP JSON branch of `terminal_get_or_ws` is
//! described here.
//!
//! `paths(...)` references handlers by full path so the per-handler `__path_*` items
//! (generated by `#[utoipa::path]` in their home module) resolve.

#![forbid(unsafe_code)]

use shared::BearerAddon;
use utoipa::OpenApi;

// Schema types referenced by `components(schemas(...))` (bare names need them in scope).
use crate::execute::{ExecuteRequest, ExecuteResponse};
use crate::files::{
    ArchiveRequest, CwdRequest, Entry, ListResponse, MoveRequest, PathBody, ReplaceRequest,
    WriteRequest,
};
use crate::snapshot::RestoreResponse;
use crate::terminals::{CreateResponse, DeleteResponse, TermInfo};

/// The runtime tool-surface OpenAPI document (merged into the broker's).
///
/// `info` is intentionally empty here — the broker's document supplies `title`/`version`
/// (pinned to the broker crate version, issue #75 Q4). Only `paths` + `components` are
/// merged in by the broker. The shared Bearer scheme is registered via [`BearerAddon`]
/// so gated runtime ops show the 🔒 (and resolve after merge).
#[derive(OpenApi)]
#[openapi(
    paths(
        crate::execute::execute,
        crate::files::get_cwd,
        crate::files::set_cwd,
        crate::files::list_dir,
        crate::files::read_file,
        crate::files::write_file,
        crate::files::mkdir,
        crate::files::move_entry,
        crate::files::delete_entry,
        crate::files::view_file,
        crate::files::replace,
        crate::files::grep,
        crate::files::glob_search,
        crate::files::archive,
        crate::files::upload,
        crate::files::tool_download,
        crate::files::tool_list,
        crate::files::tool_list_root,
        crate::files::tool_exists,
        crate::files::tool_upload,
        crate::files::list_ports,
        crate::snapshot::snapshot,
        crate::snapshot::restore,
        crate::terminals::create_terminal,
        crate::terminals::list_terminals,
        crate::terminals::terminal_get_or_ws,
        crate::terminals::kill_terminal
    ),
    components(schemas(
        ExecuteRequest, ExecuteResponse, RestoreResponse,
        TermInfo, CreateResponse, DeleteResponse,
        CwdRequest, WriteRequest, PathBody, MoveRequest, ReplaceRequest, ArchiveRequest,
        ListResponse, Entry,
        shared::ErrorResponse
    )),
    modifiers(&BearerAddon)
)]
pub struct RuntimeApiDoc;

/// Build the runtime tool-surface OpenAPI document (consumed by the broker's
/// `openapi_document()` via [`OpenApi::merge`]).
#[must_use]
pub fn openapi_document() -> utoipa::openapi::OpenApi {
    RuntimeApiDoc::openapi()
}
